### ISSUE TITLE
[Errno 13] Permission denied: '/home/nobody/.cache/Python-Eggs/..'

### ISSUE THREAD

**Issue by mbhoek** [binhex/arch-deluge#4]
If I use a ```-e PUID``` and ```-e PGID``` other than (the default) 0,
and I try to enable a plugin from the web interface,
the plugin is not enabled and
the docker log shows the following error:

```
ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Errno 13] Permission denied: '/home/nobody/.cache/Python-Eggs/Label-0.2-py2.7.egg-tmp'

The Python egg cache directory is currently set to:

  /home/nobody/.cache/Python-Eggs

Perhaps your account does not have write access to this directory?  You can
change the cache directory by setting the PYTHON_EGG_CACHE environment
variable to point to an accessible directory.
``` 

Might be related to commit d5c45e8d567d7a531bbd4a66d71e4aabb6e78390.

**Comment by binhex** [comment]
im not sure why your seeing this, in my testing i dont seem to be able to reproduce, however i have now moved the order around a little bit to see if this fixes the issue, image is built so please pull down and let me know if it fixes the issue.

**Comment by mbhoek** [comment]
Yes, that fixed it; plugs can now be enabled and no more errors in log. Thanks!
